version: "3.9"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            -   "5432:5432"

volumes:
    pgdata: