name: Automated API tests using Postman CLI

on:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "master" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
      - uses: isbang/compose-action@v1.4.1
        
      - name: Run API tests
        run: |
          postman collection run "21909072-6db76dfb-17ed-4abb-a84d-0a68d1a33c85"
